constants = {
    'SECRET' : 'PRIVATE_KEY_GOES_HERE',
    'PERIOD_IN_SECONDS' : 1,
    'WINDOW_TITLE' : 'Identifier #580CD2E889BD - Onett Art Museum Main Entrance',
    'BORDER_THICKNESS' : 10,
    'ICON_SIZE_X' : 50,
    'ICON_SIZE_Y' : 50,
    'NUM_COLS' : 8,
    'NUM_ROWS' : 4,
    'MY_RED' : (255, 0, 0),
    'MY_ORANGE' : (255, 127, 0),
    'MY_YELLOW' : (255, 255, 0),
    'MY_GREEN' : (0, 255, 0),
    'MY_BLUE' : (0, 0, 255),
    'MY_VIOLET' : (75, 0, 130),
    'MY_BROWN' : (102, 51, 0),
    'MY_GREY' : (40, 40, 40),
    'MY_BLACK' : (0, 0, 0),
    'MY_WHITE':  (255, 255, 255),
    }

number_color_dict = {
    '0': constants['MY_RED'],
    '1': constants['MY_RED'],
    '2': constants['MY_ORANGE'],
    '3': constants['MY_ORANGE'],
    '4': constants['MY_YELLOW'],
    '5': constants['MY_YELLOW'],
    '6': constants['MY_GREEN'],
    '7': constants['MY_GREEN'],
    '8': constants['MY_BLUE'],
    '9': constants['MY_BLUE'],
    'a': constants['MY_VIOLET'],
    'b': constants['MY_VIOLET'],
    'c': constants['MY_BROWN'],
    'd': constants['MY_BROWN'],
    'e': constants['MY_GREY'],
    'f': constants['MY_GREY']
}